version: "3"

services:

 strapi:

   build: .

   # == MongoDB Atlas configuration ==

   environment:

     NODE_ENV: development #(production, staging, development, etc.)

     DATABASE_CLIENT: mongo

     DATABASE_HOST: 127.0.0.1 #(e.g. : cluster3.abc65.mongodb.net if you are using MongoDB Atlas)

     # — NOTE —

     # If you have a MongoDB connection string like ‘mongodb://srv…’, it means DATABASE_SRV is ‘true’.

     DATABASE_SRV: "true" #(‘true’ or ‘false’, please note that it MUST be string or null)

     DATABASE_PORT: 27017 #(e.g. : 27017)

     DATABASE_NAME: myStrapiApp #(e.g. : myStrapiApp)

     DATABASE_USERNAME: admin #(e.g. : admin)

     DATABASE_PASSWORD: password

     # — NOTE —

     # When using MongoDB Atlas, DATABASE_SSL must be set to ‘true’. Otherwise (local MongoDB) set it to ‘false’.

     DATABASE_SSL: ‘false’ #(‘true’ or ‘false’, please note that it MUST be string or null)

     # AUTHENTICATION_DATABASE: admin

     CORS_ORIGIN: ALLOWED_CORS_ORIGIN #(e.g. : http://192.168.1.5:8000,http://192.168.1.5:3000,http://192.168.1.16:1337)

     ADMIN_JWT_SECRET: 0e602742-8310-47f0-bd8f-654d9537681b #(e.g. : ErhxCk10YqNCImwodl5Ml/Maqnw46oTyLjr+9Na4bjmJSLVWnCS90BJRAAkLsspj98caylAJgikBO9ZS0jEiOQ==)

   ports:

     ['1337:1337'] #(Specify host port and container port, format => host port:container port. e.g. : ‘1337:1337’)

     # — NOTE —

     # ‘HOST_PORT’ is the port that will be exposable to the public.

     # ‘CONTAINER_PORT’ is the internal port in which the app will be running on.